### ISSUE TITLE
[功能請求] 排序使用YT/Twitch兩者較高者

### ISSUE THREAD

**Issue by hlku** [TaiwanVtuberData/TaiwanVTuberData-Preact#7]
排序可否不單純用Youtube訂閱來排序?
而是Youtube跟Twitch取較大值來排序
因為有些以Twitch為主的V，在Twitch都已經有萬人追隨，但YT可能沒在經營而只有幾百訂閱
但這種V在排序就會被排到非常非常下面

**Comment by nh60211as** [comment]
> 目前確認已有
> 
> 1. YouTube 訂閱人數 + Twitch 追隨人數 ( https://taiwanvtuberdata.github.io/all/CombinedCount.html )
> 2. YouTube 訂閱人數 ( https://taiwanvtuberdata.github.io/all/YouTubeSubscriberCount.html )
> 3. Twitch 追隨人數( https://taiwanvtuberdata.github.io/all/TwitchFollowerCount.html )

轉為使用 react-data-table-component 後尚未實作"YouTube 訂閱人數 + Twitch 追隨人數"的排序方式。

**Comment by nh60211as** [comment]
Resolved with #19.
